const light="https://6109kentei.thebase.in/items/152161314",standard="https://6109kentei.thebase.in/items/152344793",proposal="https://docs.google.com/forms/d/e/1FAIpQLSd-dsCGZZ_4IYSzju4MT14z73Azl-CI85iFAbFC0mzcmfdTxg/viewform?usp=publish-editor";
const cases=[['A','月平均 約5名','約72,000円','仕事の合間にスマートフォンから添削'],['B','毎月 約8名','約39,000円','取り組みやすい級をすき間時間で運営'],['C','月平均 約7名','約27,000円','添削なしの動画講座を運営'],['D','月平均 約8名','約39,000円','動画講座で無理なく運営']];
const work=['講座企画・対象者・ゴールの設計','カリキュラムと教材の作成','動画収録用台本の作成','販売ページの作成・設置','申込み・決済の仕組みづくり','協会メルマガ等での募集支援'];
const Button=({href,children,kind='primary'}:{href:string,children:React.ReactNode,kind?:string})=><a className={`button ${kind}`} href={href} target="_blank" rel="noreferrer">{children}<span>→</span></a>;
export default function Home(){return <main>
<header><a className="brand" href="#top"><span><img src="/koeaca/koe-academy-logo-sheet.png" alt="声の表現アカデミー"/></span><b>開講パック</b></a><nav><a href="#results">購入者実績</a><a href="#service">制作内容</a><a href="#price">料金</a><a href="#faq">FAQ</a></nav><a className="mini" href={light} target="_blank">申し込む</a></header>
<section className="hero" id="top"><div><p className="campaign"><b>2026年8月31日まで</b><span>合計5名様限定</span></p><p className="eyebrow">資格を「仕事」に変える、オンライン講座開講パック</p><h1>プロフェッサー資格を取った。<br/><em>次は、「私の講座」を持つ。</em></h1><p className="lead">あなたの資格と経験を、<strong>実際に申込みを受け付けられる講座</strong>へ。企画から教材、販売ページ、決済、募集まで、声の表現アカデミーが形にします。</p><div className="actions"><Button href={light}>ライトプランで申し込む</Button><a href="#price">2つのプランを比較する</a></div><small>月額固定費0円／ライトプラン 132,000円（税込）から</small></div><aside className="future"><small>FROM QUALIFICATION TO BUSINESS</small><strong>資格を持っている人</strong><i>↓</i><strong>自分の商品を持つ講師</strong><p>講座内容も販売の仕組みも、一人で用意する必要はありません。</p></aside></section>
<section className="section results" id="results"><Title en="RESULTS AFTER PURCHASE">この開講パックを購入して<br/><em>講座を作った方の実績です。</em></Title><p className="intro">開講パックで講座を作り、販売できる状態にしたことで、継続的な申込みにつながっています。</p><div className="caseGrid">{cases.map(c=><article key={c[0]}><p className="person"><b>{c[0]}</b> プロフェッサー</p><h3>{c[1]}<small>のお申込み</small></h3><p className="income">月平均受領額<strong>{c[2]}</strong></p><small>{c[3]}</small></article>)}</div><p className="note">※掲載内容は個人の実績・感想であり、申込み数・売上・成果を保証するものではありません。</p><div className="strip"><b>あなたも「自分の商品を持つ講師」へ。</b><a href="#price">プランを選んで申し込む →</a></div></section>
<section className="section service" id="service"><Title en="WE BUILD YOUR COURSE">ホームページだけでも、教材だけでもない。<br/><em>講座として売れる状態まで作ります。</em></Title><div className="roles"><article><h3><small>声の表現アカデミーが行うこと</small>企画・制作・設置・募集支援</h3><ul>{work.map(x=><li key={x}>{x}</li>)}</ul></article><article className="teacher"><h3><small>あなたにお願いすること</small>経験を伝え、教えること</h3><ul><li>作成した内容を確認する</li><li>ご自身の経験や考えを加える</li><li>台本を見ながら動画を収録する</li><li>必要な場合のみ、添削や受講者対応を行う</li></ul><p>「何を伝えたいか」と「教えること」に集中してください。</p></article></div><p className="busy"><b>忙しい方にも</b> 毎週決まった打合せは不要。動画のみ・添削なしの講座も選べ、ご都合に合わせて準備できます。</p></section>
<section className="section flow"><Title en="14-DAY LAUNCH PLAN" center>朗読検定対策講座なら、<br/><em>最短14日で募集開始。</em></Title><ol>{[['1','DAY 1–3','講座案を決める','資格・経験を伺い、対象者、ゴール、受講料を具体化。'],['2','DAY 4–9','教材と台本を作る','協会側で教材・台本を作成。内容をご確認いただきます。'],['3','DAY 10–14','販売ページを公開','申込み・決済を設置し、協会メルマガ等で募集開始。']].map(x=><li key={x[0]}><b>{x[0]}</b><div><small>{x[1]}</small><h3>{x[2]}</h3><p>{x[3]}</p></div></li>)}</ol><p className="note">※講座内容や準備状況により期間は異なります。</p></section>
<section className="section bonus"><div><span>8/31までの限定特典</span><h2>お持ちの資格に合った、<br/><em>あなただけの案内・受付ページ</em>を作成。</h2><p>朗読検定、読み聞かせ検定、音読ヘルストレーナー認定講座、ボイスバイエル®入門講座など。複数資格をお持ちの場合は、資格の数に応じて作成します。</p></div><aside><b>2026.8.31まで</b><strong>合計5名様限定</strong><small>プロフィール、講座案内、申込み窓口まで一つのページに。</small></aside></section>
<section className="section price" id="price"><Title en="CHOOSE YOUR PLAN" center>月額固定費は、<em>0円。</em></Title><p className="intro center">企画・教材・台本・販売ページ・決済・募集支援は、どちらにも含まれます。</p><div className="plans"><Plan name="ライトプラン" value="132,000" fee="49.5%" href={light} featured><b>累計売上135,000円達成後</b><span>翌月から販売手数料 <strong>29.5%</strong>へ</span><small>追加費用・変更手続き不要</small></Plan><Plan name="スタンダードプラン" value="198,000" fee="29.5%" href={standard}><b>開講直後から29.5%</b><span>販売が増えても同じ手数料率</span><small>月額固定費0円</small></Plan></div><p className="note center">販売手数料には協会運営・プラットフォーム等の費用を含みます。受講料無料の講座には販売手数料がかかりません。</p></section>
<section className="section faq" id="faq"><Title en="FAQ" center>よくあるご質問</Title><div>{[['まだ講座内容が決まっていなくても申し込めますか？','はい。資格・経験・得意分野を伺い、「誰の、どんな悩みを解決する講座にするか」から一緒に組み立てます。'],['時間をかけられなくても大丈夫ですか？','はい。企画、教材、台本、販売ページは協会側で制作します。毎週決まった打合せも不要です。'],['動画・ライブどちらにも対応していますか？','はい。どちらにも対応しています。添削なしの動画講座も開講できます。'],['月額費用はかかりますか？','月額固定費は0円です。申込みがあった場合のみ、受講料から販売手数料を差し引きます。'],['ライトの手数料はずっと49.5%ですか？','いいえ。累計売上135,000円に達した翌月から29.5%へ自動で引き下げます。'],['キャンセルや返金はできますか？','お申込み確定後のキャンセル・返金は承っておりません。不明点は申込み前に無料講座案フォームからご相談ください。']].map(x=><details key={x[0]}><summary>{x[0]}</summary><p>{x[1]}</p></details>)}</div></section>
<section className="section final"><p>資格を持っている人から、</p><h2>「自分の商品を持っている講師」へ。</h2><b>2026年8月31日まで・合計5名様限定</b><div><Button href={light} kind="white">ライトプランで申し込む</Button><Button href={standard} kind="ghost">スタンダードプランで申し込む</Button></div><a href={proposal} target="_blank">迷っている方は、無料の講座案を受け取る（約3分）</a></section>
<footer><span>声の表現アカデミー 開講パック</span><small>© 声の表現アカデミー</small></footer>
</main>}
function Title({en,center=false,children}:{en:string,center?:boolean,children:React.ReactNode}){return <div className={`title ${center?'center':''}`}><span>{en}</span><h2>{children}</h2></div>}
function Plan({name,value,fee,href,featured=false,children}:{name:string,value:string,fee:string,href:string,featured?:boolean,children:React.ReactNode}){return <article className={`plan ${featured?'featured':''}`}><span className="badge">{featured?'まず小さく始めたい方に':'手数料を最初から抑える'}</span><h3>{name}</h3><p className="value"><b>{value}</b>円（税込）</p><p className="fee">販売手数料<strong>{fee}</strong></p><div className="step">{children}</div><Button href={href} kind={featured?'primary':'outline'}>{name}で申し込む</Button></article>}
